debug: Add missing "use DateTimeZone" in LegacyLogger.php
Seen in fatal.log in production: ErrorException from line 264 of
/srv/mediawiki/php-1.26wmf1/includes/exception/MWExceptionHandler.php:
Fatal Error: Class undefined: MediaWiki\Logger\DateTimeZone

Bug: T95727
Change-Id: Icb303314caaef47ac767fbf593e92d09e818f147