Do not crash on invalid codepoint references in style attributes.
An invalid codepoint reference causes the parser to crash with a
fatal error: "Asked for code outside of range (1114112)"

The patch validates the codepoint and substitutes invalid ones
with a replacement character.

As a side note, maybe style attributes should be normalized
after processing, but that's a separate issue.

Change-Id: I3fa8fe33f7acb68f357a5726f2de5140b0f7153d