MWException: restore prior render() logic
Partially revert 00bee02 by restoring the prior MWException::report()
logic. MWExceptionRenderer does not handle all of the MWException
subclasses that somehow modify the default render() behavior. Notable
among these is Flow\Exception\FlowException and its subclasses which
modify the `$wgOut` global to divert HTML output to alternate locations.

Bug: T147122
Depends-On: I2c90e2d9e9b019357458c7e14a3d602b591c6f5b
Change-Id: Ibe3cadca229ce21ed0a3a2482433e3a22b5f5646
(cherry picked from commit eeb382e3c7addd13ee70a58542412628e884f8ec)