maintenance: Make updateCredits a proper MW maintenance script
Why:

- Running maintenance/updateCredits.php with MediaWiki's script
  runner would not work as expected because it wasn't actally a
  proper MW maintenance script. So the docs on the manual page
  https://www.mediawiki.org/wiki/Manual:UpdateCredits.php are a
  bit misleading when trying to use `php run.php ...`.

- When trying to run this script before this patch, an error is
  thrown like:

  ERROR: The script file '/maintenance/UpdateCredits.php' cannot
  be executed using MaintenanceRunner.
  It does not set $maintClass and does not return a class name.
  Try running it directly as a php script: php /maintenance/UpdateCredits.php

  This is because the script had not been converted to use our
  MaintenanceRunner base class.

What:

- This patch makes the script use MaintenanceRunner as we do it
  for other scripts.

Change-Id: I135adaedc8862127229aba0582722d9b691f6452