Disabling profiling in the debug toolbar for ProfilerSimple (for now)
Throws a fatal error when using a ProfilerSimple subclass and the
debug toolbar (the problem is that $this->mCollated doesn't have
the same format in both cases):

Warning:  Invalid argument supplied for foreach() in includes/profiler/Profiler.php on line 625

Fatal error:  Unsupported operand types in includes/profiler/Profiler.php on line 633

Change-Id: I7f2bc714396a9249193a5828c154e09f7e0b5230