AutoLoader: Reduce generateAutoload.php crashes
Quite often when moving a class, generateAutoload.php
doesn't work due to a crash early on, like so:

```
Error: Class "Wikimedia\MapCacheLRU\MapCacheLRU" not found
from /mediawiki/includes/language/LanguageFactory.php
at /mediawiki/includes/ServiceWiring.php
at …
at /mediawiki/includes/MediaWikiServices.php
at /mediawiki/includes/session/SessionManager.php
at /mediawiki/includes/Setup.php
at /mediawiki/maintenance/doMaintenance.php
at /mediawiki/maintenance/generateAutoload.php
at {main}
```

The SessionManager::singleton() call in Setup.php is responsible
for indirectly initiating a large number of classes in MediaWiki.

Fortunately, it can be skipped by setting MW_NO_SESSION_HANDLER=1.
We do this in the Installer to operate MediaWiki in a minimal state.
This seems appropiate for generateAutoload.php too.

Change-Id: I75d33f7fb185a5820ac7a746105b2d846fb8daa0