UsageException: Validate that $codestr is a non-empty string
Current theory on T138585 is that something is passing in false, so
let's throw an InvalidArgumentException that should log a backtrace for
us.

Bug: T138585
Change-Id: Iba0dad424c56340b8bc73322bb1a7ae6d4de314a
(cherry picked from commit 27f652644ce64b86d5a8701e8010b3c61ae062ac)