DBConnectionError: Expand {{SITENAME}} in pagetitle with Message::text()
Follows-up 485ff9ead94b by making the same change in DBConnectionError,
which overrides MWException::msg() to not use database messages.

Bug: 58447
Change-Id: Iafa9dd741f1f099a4a6cfb8cf655b7d5f504011a