Update git submodules
* Update extensions/Wikibase from branch 'wmf/1.45.0-wmf.23'
  to b356e12ff51d264d8bc8d1bdb2f2f5c542848884
  - Restore "Implement new usage types for statement with qualifiers and references"
    
    This reverts commit 4225a33ca65c5e32ce9368f46e518e97009044d2.
    
    Reason for revert: Caused production errors due to existing usage in database:
    > InvalidArgumentException: $aspect must use one of the XXX_USAGE constants, "CQR" given!
    
    Bug: T401290
    Bug: T407684
    Bug: T407744
    Change-Id: I03833a75495ea6f3a4d36f2c6bf9fefd849fd3b9