Pass $title parameter to getCredits() call
Fixes:
Warning:  Missing argument 3 for CreditsSourceAction::getCredits(), called in /usr/local/apache/common-local/php-1.23wmf6/includes/SkinTemplate.php on line 445 and defined in /usr/local/apache/common-local/php-1.23wmf6/extensions/CreditsSource/CreditsSource_body.php on line 40
Fatal error:  Call to a member function getArticleID() on a non-object in /usr/local/apache/common-local/php-1.23wmf6/extensions/CreditsSource/CreditsSource_body.php on line 48

Change-Id: I8edbdfe615f848963e3bea47dac99d1abd64c7f7
(cherry picked from commit ddd0b4ab97305b6bc2ca39f2062dd0a90b2624cf)