Updated mediawiki/core Project: mediawiki/extensions/ContentTranslation  a05b5574ba8506676c3b710ce0586d7c8a69eb37
Try to avoid JS error

TypeError: details.edit.code is undefined ext.cx.publish.js:305:1

Reported in https://www.mediawiki.org/wiki/Topic:T0vj02va30kdelc2

Change-Id: Id3f915b9d8c7eeb6bf8eeea3890b381c16d40356
(cherry picked from commit 0776359989bb31977bec6198ffcfc00c9acf4433)