build: Enable karma debug log and use progress reporter
Should help diagnostic of QUnit failures such as:

    Error: Pending AJAX requests: 0 (active: 1)

Change-Id: I0ed1c8f0c26d49fa13dab2d9de20181d48ee2932
(cherry picked from commit fa63a70ae90c8e82d70932ac13eae51083f4a06a)