tests: Avoid stacktrace for outdated composer dependency message
Since 65d62ae39e errors from maintenance scripts are converted to
exceptions for phpunit runs,
this also includes the composer-lock-up-to-date check in phpunit.php
because it is running after MW_PHPUNIT_TEST is defined.

As a developer I assume a php fatal from my code changes when getting
stacktrace printed on phpunit runs. Also I have to read back the screen
to see the real issue, but it is not a php fatal.

Catching the exception and calling exit() avoids the stacktrace and
gives the plain error message back to see the problem faster.

When running the check before setting MW_PHPUNIT_TEST,
the autoloader is not ready and the script is not found.
Reuse code via TestSetup class

Error: your composer.lock file is not up to date. Run "composer update"
to install newer dependencies
PHP Fatal error:  Uncaught MediaWiki\Maintenance\MaintenanceFatalError
in maintenance\includes\Maintenance.php:568
Stack trace:
#0 maintenance\checkComposerLockUpToDate.php(73):
MediaWiki\Maintenance\Maintenance->fatalError('Error: your com...')
#1 tests\phpunit\phpunit.php(171): CheckComposerLockUpToDate->execute()
#2 {main}
  thrown in maintenance\includes\Maintenance.php on line 568

Follow-Up: I554a963c63eb4f22ebb3273053a7b83a33dcb4d1
Change-Id: I7b26038453f8305e250b6abfee34c64c220c4336