Permissions: Add strict return types and minor doc cleanup
Fix broken tests because:
> TypeError: Return value of
> PermissionManager::getNamespaceRestrictionLevels() must be of the
> type array, boolean returned

Change-Id: I1546ffda7fafe23bccfa6d8792fc8cf95bbbb43b