exception: Add newline at the end of a debugging line for CLI users
Bug: T162315
Change-Id: Ia2963fa298ab0e4782ef823e7f53322cd6a9c99b
(cherry picked from commit 842b7a176985f4c1215b72f2eab7527ccbb8fbdc)