TypeError: Unsupported operand types: array + null
Some skins do not support the notification menu so in this case it
would be empty. Safeguard against this by checking.

Since I3abf7b4142f1edd7cd684db4b25331af0439e129 legacy Vector merges
the notifications menu with the user-menu and unsets the notification
key so it no longer exists in SkinVectorLegacy::runOnSkinTemplateNavigationHooks L38-L48.

Note: There may be further follow up needed, as we optimize
skin rendering but let's address this immediate problem.

Bug: T416619
Change-Id: Id7fe13bd7ca38885a57971a6d53ce57255e3b9ec
(cherry picked from commit d54173f1d56031c9a0469dea75bd7bdb4ca22c35)