mediawiki.widgets.CategorySelector: Add missing dependency for ForeignApi and Title
Follows-up e6d1550309 which attempted to backport 86dedeea7f but
left out the dependencies.

Fixes fatal error in REL1_26 qunit tests:
> Exception in module-execute in module mediawiki.widgets.CategorySelector
> TypeError: Expecting a function in instanceof check, but got undefined

Bug: T125335
Change-Id: I6e5834c3098d00bfc75e9f6b0d61ed6e5babc6ca