Revert "Convert MultiHttpClient to use Guzzle"
That breaks on Wikimedia beta cluster (T217733):

Warning: Invalid argument: option: 6 in
vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 56

Warning: Invalid argument: option: 6 in
vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 56

Warning: Invalid argument: function: not string, closure, or array in
vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 108

Fatal error: Uncaught exception 'ConfigException'
Failed to load configuration from etcd: cURL error 23: Failed writing
header

This reverts commit 1e048a08b565ae909e85465f8b09a27ed8480ce2.

Bug: T202352
Bug: T217733
Change-Id: I2384355043896128d3f191941e8da00fdc62361e