Updated mediawiki/core Project: mediawiki/extensions/UploadWizard  4d3c4ccdb6f607f85be42524ef79b8c5955eed4f
uw.controller.Details: Fix 'Uncaught TypeError: this.copyMetadataWidget.remove is not a function'

Follow-up to 189a5572cc08ac46dc0dba1f7293d5967ee8c7ba.

Change-Id: I333a8e0a0789cc2c0b510e4b14a719de729e8389
(cherry picked from commit c3b7af32bc541bddfeb35c92255406d347f7b24a)