exception: Support message normalisation for structured logging
Let Monolog insert exception_id and exception_url so that consumers
of logging data (such as Logstash) may provide a normalised message
that does not contain these variants, for ease of aggregation
and message trend counting.

Bug: T45086
Change-Id: I7cc8f8c9e68031ad6771593d390079c0a3a535b9