Add a null check VueComponentParser to prevent php8.1 issues
The third argument to VueComponentParser::element is null for
void elements. Trying to run preg_replace on a null string causes
a warning in php8.1. Add a check for null.

This fixes a unit failure test in php8.1:
RuntimeException: Error parsing file 'resources/skins.vector.search/App.vue'
in module 'skins.vector.search': preg_replace(): Passing null to parameter #3
($subject) of type array|string is deprecated

Bug: T313663
Change-Id: I6904b0279ecc7bada3f8203a165307c17e5ee795
(cherry picked from commit 4c432b6ad57e44407cb36b43c37f9ea06793c669)