phpunit: Fix failing FileRepo tests on BSD/Darwin
I encountered it with PHP 8.5 on macOS, but might affect Linux and/or
older PHP versions as well.

> InvalidArgumentException: Not in temp dir: /private/tmp/foo outside /tmp

Our code hasn't changed recently, but it seems to have behaved this
way for a while:

```
$ php -a // PHP 8.1 on macOS
php > echo tempnam('/tmp', 'foo');
/private/tmp/foobrgp16

$ php -a // PHP 8.2 on macOS
php > echo tempnam('/tmp', 'foo');
/private/tmp/fooyi3rGP

$ php -a // PHP 8.3 on macOS
php > echo tempnam('/tmp', 'foo');
/private/tmp/fooilTmhg

$ php -a // PHP 8.5 on macOS
php > php > echo tempnam('/tmp', 'foo');
/private/tmp/foor5mh7k9galkibdsRiCs
```

Bug: T371719
Change-Id: I7afc92ecf9ed84ee05ab94bda1962e1f24b81b2b
(cherry picked from commit 97c06b6fef8d5f6170892afec495b759c9975f37)