Fatal error: Call to a member function formatDuration() on a non-object in SpecialUserlogin.php on line 818
Bug: 53246
Change-Id: Ie2b23cefe569b31c2da67e16077d4557c6247bc9
(cherry picked from commit 01bb5cac0780032e48e2f5893f820ea9380f540c)