HttpError: Convert line breaks in text message to <br>
Used by MediaWiki::tryNormaliseRedirect() for example with plain text
containing line breaks.

Change-Id: I5949046af4065c5536080212b96374466849b91a