Restore recentchanges.rc_cur_time (breaks psql)
This reverts commit 974562aee92a78be82cf8e1416ef44648bb7dbb7.

Removing rc_cur_time from SQL statements causes
this error when installing a new wiki on PostgreSQL:

Query: INSERT INTO "recentchanges"
(rc_timestamp,rc_namespace,rc_title,rc_type,rc_source,rc_minor,rc_cur_id,rc_user,rc_user_text,rc_comment,rc_this_oldid,rc_last_oldid,rc_bot,rc_ip,rc_patrolled,rc_new,rc_old_len,rc_new_len,rc_deleted,rc_logid,rc_log_type,rc_log_action,rc_params,rc_id)
VALUES ('2013-12-04 10:54:26
GMT','0','Main_Page','1','mw.new','0','1','0','MediaWiki
default',,'1','0','0','127.0.0.1','0','1','0','524','0','0',NULL,,,'1')
Function: RecentChange::save
Error: 23502 ERROR:  null value in column "rc_cur_time" violates
not-null
constraint

This is because rc_cur_time in NOT NULL with no
default value on PostgreSQL.

Conflicts:
	includes/changes/RecentChange.php

Change-Id: I66034fad8a1cf5485b5daf0421378a28ca58beab
Bug-Id: 40667