maintenance: Require BootstrapHelperFunctions after php version check
The global functions in BootstrapHelperFunctions are not compatible with
older php syntax and require the files fails

PHP Parse error:  syntax error, unexpected '?', expecting variable
(T_VARIABLE) in includes\BootstrapHelperFunctions.php on line 30

Also use older syntax in run.php

PHP Parse error:  syntax error, unexpected ')' in maintenance\run.php on
line 47

The expected error:
Error: You are using an unsupported PHP version (PHP 7.0.0).
MediaWiki 1.47 needs PHP 8.3.0 or higher.

Check if you might have a newer PHP executable with a different name.

Change-Id: I9afd61f751280fe8686641ab8fb64b24e2f42c4a