[WIP] WebStart: Remove use of realpath() for $IP
When installing MediaWiki in a sub directory of document root,
and including it from an /index.php file in the document root,
MediaWiki succesfully includes WebStart from index.php, but
WebStart.php fails to include Setup.php.

Example:
* /var/www/mediawiki - MediaWiki installation
* /var/www/index.php - Containing:

```
<?php
require __DIR__ . '/mediawiki/index.php';
```

Failure:

> Fatal error:  require_once(): Failed opening required '/var/www/includes/Setup.php' (include_path='.:/usr/local/lib/php') in /var/www/mediawiki/includes/WebStart.php on line 97
> Stack trace:
>   1. {main}() /var/www/index.php:0
>   2. require() /var/www/index.php:3
>   3. require() /var/www/mediawiki/index.php:40

Change-Id: Icd8cfa580ce1c22bc3bf177570a9f4a940d2427c