MWException: Don't send headers multiple times
Ideally we wouldn't have sent headers yet, but in some weird
code paths where we output stuff raw (like Export) we might
have already sent them.

All depends on when the failure happened.

Should silence all of the "headers already sent" being seen
from exports.

Change-Id: I12e0532e93d30b2255f73a9d0e017c73e30c3e28
(cherry picked from commit cfbeb437a3bf688f07681d8b900f3d0a13f25497)