exception: Prefix error type in front of error message
Follows-up 399ba2fecf which didn't include any translation of the error
type in the logged message (e.g. "PHP Notice" or "PHP Warning").

Before
 Error from line 2130 of mediawiki/includes/OutputPage.php: Undefined variable: bar
 Error from line 2130 of mediawiki/includes/OutputPage.php: strpos() expects at le..

After
 Error from line 2130 of mediawiki/includes/OutputPage.php: PHP Notice: Undefined variable: bar
 Error from line 2130 of mediawiki/includes/OutputPage.php: PHP Warning: strpos() expects at le..

Based on the log formatter in php
 https://github.com/php/php-src/blob/0f5858e3a328/main/main.c#L1086-L1119

Change-Id: I52f98e52caa64955050ed73e1acbc78b1116a9fd