Parser: Deprecate use of mOutput before initialization
In some extensions they check that getOutput returns null
if it does they return early.  For example:

https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5579

But with the type change in I247643b9bf0cabdc92a7e893d653edeaed9a1307
(MW 1.41.0), that attempt fails with the following:

```
Error: Typed property Parser::$mOutput must not be accessed before initialization
```

Fix this by allowing Parser::getOutput() to return null,
but emit a deprecation warning to notify users that the
Parser object has not been property initialized at this
point.

Change-Id: I0de2cf0381ceac36374a47fb11e260b1c522353b