DBQueryError: Remove incorrect message parameters
This array is passed as parameters to Message, but this is not a valid
format, so it was ignored. It doesn't seem necessary, so just remove
it. Follow-up to 2387b0c774e84f407233e30d974047dc7300a664.

Change-Id: I90d5a21b174f0d32aa80b5a77f8129f5fc666e3b