exception: Remove ErrorException workaround in handleFatalError()
Follows-up 115df551f2 and its CR (Gerrit I664bfe55359aadb343ee7).

The comment was out of date.

* The stack is indeed unwound at this point for most use cases,
  but using debug_backtrace() doesn't help that.
  What debug_backtrace sees as the same as '(new Exception)->getTrace()'.

  The reason the code used debug_backtrace isn't to obtain a better
  trace. It was using that because HHVM gave us a magic non-standard
  '$trace' parameter into the callback. Given there is no way to
  construct the built-in Exception object with a custom trace,
  the only way we could log it was to build the rest of the array
  ourselves as well. We'd fallback for PHP 5 by back-filling only
  the trace part using debug_backtrace().

  The code for HHVM has been removed meanwhile (d1679955b4).
  What's left is standard ErrorException handling, which our
  Monolog layer should be formatting instead, not duplicated
  here.

Getting a trace here would be nice, but is out of scope for this
change. Assuming the php-wmerrors handler (php7-fatal-error.php
at WMF) sees the stack, that's where we'll get it for prod.
Within MW core under plain PHP 7 there simply isn't a way to get
it, hence php-wmerrors exists (covered in more detail at T187147,
specifically T187147#5165179).

Bug: T233342
Change-Id: Ic81076a8fd1a593460528162d4319fdedb985f30