Fix and update i18n QUnit test breakages
* mediawiki.language.test:
  Was broken for a while because the setup/teardown set
  language.data instead of language.data.values so each test
  resulted in:
  > TypeError: Cannot read property 'en' of undefined

  Also stored the copy in the QUnit module context instead
  of in the shared scope.

* mediawiki.cldr.test: Update QUnit pattern.
  - Removed redundant Initial check
  - '--' from test name
  - test()'s expect count argument
  - Superfluous comments, its just assert.equal it should go
    without saying at this point through the unit tests what
    the 2nd and 3rd are.

* mediawiki.cldr.test:
  Fixed trailing comma in commented out code and whitespace
  warnings.

Change-Id: I95de3bb551efd7993cfcfba4a5cc3f310e7d6805