resourceloader: Fix fatal when using $wgResourceModuleSkinStyles with "+"
Fatal error: [] operator not supported for strings in
includes/resourceloader/ResourceLoader.php on line 354

This would occur when a skin customized ResourceModuleSkinStyles using
the '+' syntax, which preserves default skinStyles, and the default
skinStyles was defined as a string rather than array.

Change-Id: I6cd12a638d562c75bc4704e098de84f3882248b6
(cherry picked from commit 5a5784a58d0c100c960e3a8bad08c9253b25b25a)