Update git submodules
* Update extensions/DonationInterface from branch 'deployment'
  to 84fe084d15884c3979a4c5b17f5ff98cd3607f23
  - Merge branch 'master' into deployment
    
    9b2b8bb3b Send phonetic name fields through on queue messages
    0681b9106 Handle card submission in DLocal in DonationInterface
    e25736435 build: Remove syntax option from stylelint
    7fe549d8f Fix some whitespace in Dlocal adapter
    dd98dcbd1 Add description parameter to dlocal authorize
    c7447d303 Remove deleted hook MediaWikiPHPUnitTest::startTest
    56ca38dc4 Update SmashPig dependency and own version
    d7461e440 Localisation updates from https://translatewiki.net.
    
    Change-Id: Ide75af42eb205cb5beef599af016edd7a060fc0f
    
  - Localisation updates from https://translatewiki.net.
    
    Change-Id: I3018a2df6ba4cf3e654a9ebcf2edd6b8ef27e1ba
    
  - Update SmashPig dependency and own version
    
    Change-Id: I21ec08da2dc110a53dba2cbdf995372a0ed375ea
    
  - Remove deleted hook MediaWikiPHPUnitTest::startTest
    
    This hook was removed in 6e4a17b1be302ce4ac2b09f54fcc83da010bd53f. The hook isn't running so it clearly is not needed anymore.
    
    Change-Id: Id637df335590a96371faeba565305bf4a95d2d9b
    
  - Merge "Add description parameter to dlocal authorize"
  - Merge "Send phonetic name fields through on queue messages"
  - Merge "Fix some whitespace in Dlocal adapter"
  - Add description parameter to dlocal authorize
    
    Change-Id: I92ae8fec842e25fe9232c3691bbc8783d89457d5
    
  - Fix some whitespace in Dlocal adapter
    
    And loosen up one typehint in anticipation of non-card methods
    
    Change-Id: I2288e17904762680a78a983c7d9157e388db789a
    
  - build: Remove syntax option from stylelint
    
    Error: The "syntax" option is no longer available. You should install an
    appropriate syntax, e.g. postcss-scss, and use the "customSyntax" option
    
    Change-Id: Iafc7bd40e8db1e21df2387dcf31558412bdd54bd
    
  - Handle card submission in DLocal in DonationInterface
    
    Bug: T324290
    Depends-On: I245788843153e8e348a3ce9b67860c47f6b28ca7
    Change-Id: I3e768bdb9f86e6f4cda441e35f4563d9bde9045d
    
  - Send phonetic name fields through on queue messages
    
    For Adyen variant=ja_02
    
    Bug: T322793
    Change-Id: If122d4ab4f62b526a28048a6624be8c1b5d3d5a4