DatabaseUpdater: Don't fail on first-class-callable-syntax
method_exists() expects a string as second parameter. Therefor check
for is_string() instead of !is_array(). This allows to use the
first-class-callable-syntax for $func without run into the error:

TypeError: method_exists(): Argument #2 ($method) must be of type
string, Closure given

Change-Id: I6823d9dd127d299615697c880bd3d169c223e2fd