Updated git submodules
Project: mediawiki/extensions/ContentTranslation wmf/1.28.0-wmf.12 965b81a64f31a49d05d4bd82841c7dfb0a9668a8

DumpCorpora: Skip JSON formatting for old PHP versions

MediaWiki tries to fix up the PHP's JSON output failing miserably:
Fatal error: Out of memory (allocated 9417523200) (tried to allocate
18446744071930920519 bytes)

Bug: T127793
Change-Id: I6897fa496a8f85c92c0e870999f774d42123be1f
(cherry picked from commit 9afaebd6f33399000370fd33a09ef93b559cbba3)