mw.Api: Add better error message for HTTP 429 errors
Instead of the default message for HTTP errors ("Server returned
error: HTTP 429"), format a more helpful message explaining what
happened ("You have performed too many actions in a short period
of time") and the required wait time, if known ("You can try again
in X hours/minutes/seconds" or "Try again later").

We don't have an equivalent of the PHP Language::formatDuration()
in JS code; implement a minimal replacement in the mw.Api code. We
can't rely on the server to supply us with better error messages,
as this is intended to handle errors generated outside of MediaWiki,
e.g. by the Wikimedia API gateway.

We have some existing localisation messages for exceeding rate limits
('apierror-ratelimited', 'actionthrottledtext'), but I think they are
not worded very well, so I added new ones. I might improve the others
in another commit later.

Bug: T418953
Change-Id: I5e07b18ab8c448ad486867ed0434f45c184da9df