Revert "Make Revision::getRevisionText() cache the converted text"
fails on beta update.php with:
Fatal error: Call to undefined method ExternalStore::decompressRevisionText() in /srv/mediawiki-staging/php-master/includes/Revision.php on line 1290
Guess ExternalStore::decompressRevisionText does not exist.

This reverts commit df3d46e57f0030cf0edbe2a9c91c8d4787908bee.

Bug: T158084
Bug: T161037
Change-Id: I52c2b359b4a995c00a5111b419041aa09f291e0e