Update git submodules
* Update extensions/DonationInterface from branch 'deployment'
  to c68b7ce7fdba036c9b412f59948ca8872371c64f
  - Merge branch 'master' into deployment
    
    08cd791a5 Localisation updates from https://translatewiki.net.
    ae7953c27 Forward compatibility change for AbstractProcessingHandler on monolog v3
    97ed8c1e5 Localisation updates from https://translatewiki.net.
    53cbff10a Update SmashPig to v.1.2.4.11
    
    Change-Id: I55d80a0328d2bf2cd1c74a6ed2f9be6a6db0dbb3
    
  - Update SmashPig to v.1.2.4.11
    
    Change-Id: Ifff1cb4bab38ad890d7812e6d31647bca80b6901
    
  - Localisation updates from https://translatewiki.net.
    
    Change-Id: I8238375d9b5669f904dae765002050d5b8ee4627
    
  - Forward compatibility change for AbstractProcessingHandler on monolog v3
    
    Fatal error: Declaration of MediaWikiLogHandler::write(array $record):
    void must be compatible with
    Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord
    $record): void
    
    Monolog\LogRecord implements ArrayAccess, usage of $record is unchanged.
    
    Bug: T397070
    Change-Id: I26ea67bd907e8da1c8279b30257c3d80f4af8712
    
  - Localisation updates from https://translatewiki.net.
    
    Change-Id: I98cb25feba3f0ca0a7fc11e0e7b1d0468a8c85fd