exception: Use const for MWExceptionHandler::$fatalErrorTypes
Also remove @var from const, the type is given by the value of the const
and does not need documentation.

Change-Id: I65636f2b97b44387c4320ebfb4be6c81d6f771b9