Fix for: Fatal error:  Call to undefined method ApiDelete::getErrorsArray()
Fatal error:  Call to undefined method ApiDelete::getErrorsArray() in /usr/local/apache/common-local/php-1.20wmf7/includes/api/ApiDelete.php on line 65

Caused by https://gerrit.wikimedia.org/r/#/c/7572/

Change-Id: Ib86fab94667ed50d172eb7ea3e82c99ecb3e52b0