exception: Send silenced errors to a new log channel with level=DEBUG
Follows-up 4f08bb3be9 (I240b75f5a4), which improved the "error" channel
to make use of the PSR-3 severity level (instead of defaulting to
ERROR).

This change exposes the suppressed errors to a new channel,
with a forced severity level DEBUG.

The formatted message is unchanged and reflects the original severity
through its "message" (i.e. "PHP Notice", "PHP Warning", etc.)

Bug: T193472
Change-Id: I34b19837c391ff4acdb55fc0c310c0f554f15da2