Revert "Improve sorting on SpecialWanted*-Pages"
This reverts commit 5b15728478f9b167389268fb988a7b9f9f78fcf5. The change causes db query errors:
DBQueryError: 1054 Unknown column qc_ra.rd_namespace in order clause

Change-Id: I068beeae70037c959d42419791911c54ca9908a1