mediawiki.page.watch.ajax depends on mediawiki.page.startup
mediawiki.page.watch.ajax.js requires mw.page, which is defined in
mediawiki.page.startup.js

I just got the error message:
  Exception thrown by mediawiki.page.watch.ajax
  TypeError: mw.page is undefined

Change-Id: I869fbcb701c3c17ecf6564d89a9bb773bd1a76bd