searchSuggest: Prevent error request.abort is not a function
The change 4ccc57ff0b297d70726f668ba6f5a4b79c8a4c72 cause the error
  Uncaught TypeError: request.abort is not a function
in the JavaScript console.

Change-Id: Id431d21e242d64245bc3722e62962a598002d44f