exception: Add "error-suppressed" channel for suppressed errors
The main "error" channel only contains non-suppressed errors.
There is an "error-json" channel that already contains all errors,
but this is discouraged from use and has formatting (JSON) incompatible
with most other channels.

Keep "error" free of suppressed errors, but introduce a new
"error-suppressed" channel that exposes these in the same format.

Bug: T45086
Change-Id: I34b19837c391ff4acdb55fc0c310c0f554f15da2