Revert "Added some constants to speed up Setup.php"
This patch causes php maintenance/getConfiguration.php  to die with a fatal
error:

Fatal error: Call to a member function isItemLoaded() on a non-object
  in includes/GlobalFunctions.php on line 1268
 
Call Stack:
  1. {main}() maintenance/getConfiguration.php:0
  2. require_once('maintenance/doMaintenance.php')
       maintenance/getConfiguration.php:196
  3. wfLogProfilingData() maintenance/doMaintenance.php:116

When calling wfLogProfilingData() the $wgUser is undefined which causes the
fatal at:

  if ( $wgUser->isItemLoaded( 'id' ) && $wgUser->isAnon() ) {
    $forward .= ' anon';
  }
  
This reverts commit 2c9de255f71501b749c2b700d0da6fc911358b62.

Change-Id: I093d8fbe2c08875808868d449a90b620cc6c94a6