exception: Add suppressed errors to "error" channel as level=DEBUG
Follows-up 4f08bb3be9, which improved the "error" channel to
make use of the PSR-3 severity level (instead of defaulting to
ERROR).

This change also exposes the suppressed errors to that channel,
with a forced severity level DEBUG.

The original severity is preserved in a new error_original_severity
field.

Bug: T45086
Change-Id: I34b19837c391ff4acdb55fc0c310c0f554f15da2