Exception: Don't use OutputPage if it is disabled
If an exception is caught at the top level after OutputPage::disable()
has been called, an empty response body is sent. So, don't use
OutputPage in that situation.

Change-Id: I8962619f85d45d3f9ee443799aca169f81ea3d99