Revert "Make MessageCache use the immutable text cache during cache rebuilds"
The change fails on beta update.php with:

Fatal error: Call to undefined method ExternalStore::decompressRevisionText() in /srv/mediawiki-staging/php-master/includes/Revision.php on line 1290

Guess ExternalStore::decompressRevisionText does not exist.

This reverts commit c2bbb51c20822b91cac4d416e0af103491bf4e7f.

Bug: T158084
Change-Id: Ifb4959a765ac7b0ea05ff176c0faee9b3a7b0c1d