tests: Change DomDocument return type in SpecialCreateAccountTest
With php8.4 the return type declaration fails the version used by parsoid.

This was changed in master (1.46) when the class was namespaced in 6e26e43825fc662405535943906a67684abec115

1) SpecialCreateAccountTest::testShouldShowTemporaryPasswordAndCreationReasonFieldsForRegisteredUser
TypeError: SpecialCreateAccountTest::getOutputHtml(): Return value must be of type DOMDocument, Dom\HTMLDocument returned

/workspace/src/tests/phpunit/includes/specials/SpecialCreateAccountTest.php:107
/workspace/src/tests/phpunit/includes/specials/SpecialCreateAccountTest.php:71

Change-Id: Ic4ed8c11e4b28af6d7d22e3de2ea46ae2970c1e7