exception: Move remaiming MWExceptionHandler tests to its test case
These were left behind during the initial sprint (344481f60d9) for
UnitTestCase as it used a global variable. Since then, UnitTestCase
has gained support for resetting these automatically for simple
cases like this. No need to bring in IntegrationTestCase for it.

Change-Id: Id8717c1f4148510ae4a67aec7a2dc0d23679a5ac