mw.loader: Don't assume var 'loading' assigns before Promise resolves
In rare situations the variable loading already assigned with a promise and
the call to loading.map fails with

  TypeError: loading.map is not a function

Change-Id: Ie50bdda229e48b159702fc2a83e641a35d7c850c
(cherry picked from commit dd140224c850e011f9c5ea4a8763c5918d4ab566)